export let option:any[] = [
    {
        name:'语种',
        type: 'languages',
        children:[
            {
                name:'全部',
                data:'-1'
            },
            {
                name:'华语',
                data:'7'
            },
            {
                name:'欧美',
                data:'96'
            },
            {
                name:'日本',
                data:'8'
            },
            {
                name:'韩国',
                data:'16'
            },
            {
                name:'其他',
                data:'0'
            },
        ]
    },
    {
        name:'分类',
        type: 'classify',
        children: [
            {
                name:'全部',
                data:'-1'
            },
            {
                name:'男歌手',
                data:'1'
            },
            {
                name:'女歌手',
                data:'2'
            },
            {
                name:'乐队组合',
                data:'3'
            },
        ]
    },
    {
        name:'筛选',
        type:'screen',
        children:[
            {
                name:'热门',
                data:'',
            },
            {
                name:'A',
                data:'a',
            },
            {
                name:'B',
                data:'b',
            },
            {
                name:'C',
                data:'c',
            },
            {
                name:'D',
                data:'d',
            },
            {
                name:'E',
                data:'e',
            },
            {
                name:'F',
                data:'f',
            },
            {
                name:'G',
                data:'g',
            },
            {
                name:'H',
                data:'h',
            },
            {
                name:'I',
                data:'i',
            },
            {
                name:'J',
                data:'j',
            },
            {
                name:'K',
                data:'k',
            },
            {
                name:'L',
                data:'l',
            },
            {
                name:'M',
                data:'m',
            },
            {
                name:'N',
                data:'n',
            },
            {
                name:'O',
                data:'o',
            },
            {
                name:'P',
                data:'p',
            },
            {
                name:'Q',
                data:'q',
            },
            {
                name:'R',
                data:'r',
            },
            {
                name:'S',
                data:'s',
            },
            {
                name:'T',
                data:'t',
            },
            {
                name:'U',
                data:'u',
            },
            {
                name:'V',
                data:'v',
            },
            {
                name:'W',
                data:'w',
            },
            {
                name:'X',
                data:'x',
            },
            {
                name:'Y',
                data:'y',
            },
            {
                name:'Z',
                data:'z',
            },
            {
                name:'#',
                data:'0',
            }
        ]
    }
]